import * as React from 'react';
const Defis = [
      'Shot or text',
      'C&aposest quoi les odds sur 4',
      '2 vérités 1 mensonge',
      'Bois de l&aposeau',
      'Shot partner',
      'Spelling bee (1 mot à épeler)',
      'Donne 1 câlin',
      'Yoga challenge',
      'Mime sans son',
      'Would you rather',
      'Face time or shot',
      'Guess the song',
      'Switch with someone',
      'Iced',
      'Ombre chinoise',
      'Change quelque chose sur toi',
      'Obtenir un double en 3 essais',
      'Trouve un objet commençant par la lettre ...',
      'Heads up',
      'Flip the bottle/ flip the cup',
      'Plus haut plus bas',
      'Plus de je (1 tour)',
      'Vape challenge',
      'Explique la nuit ou tes parents ton fait sans rire',
      'Demontre ta position sexuelle préféré sans rire',
      'Scattergories',
      'Laisse quelqu&aposun te faire un wet willie',
      'Fait 15 push-up',
      'Rajoute un nouvel ingrédient à ton verre',
      'Devient aveugle pendant 1 tour',
      'Essaie de fake cry en 2 minutes',
      'Bras fer avec la personne opposée',
      'Partage ta plus vieille photo Facebook (publique)',
      'La dague de baal'

    ];

export default Defis; 
